### ISSUE TITLE
internal links

### ISSUE THREAD

**Issue by affeldt-aist** [affeldt-aist/coq2html#10]
minor: some internal links seem broken: https://yoshihiro503.github.io/coq2html/mathcomp.classical.mathcomp_extra.html#P:4 works great but https://yoshihiro503.github.io/coq2html/mathcomp.classical.mathcomp_extra.html#T:2 doesn't
@proux01

**Comment by affeldt-aist** [comment]
this might be related to issue #11

**Comment by proux01** [comment]
Yes and fixed upstrem by https://github.com/coq/coq/pull/18527 which will land in Coq 8.20, this can be closed.
