### ISSUE TITLE
Notation after closing parenthesis

### ISSUE THREAD

**Issue by yoshihiro503** [affeldt-aist/coq2html#42]
For example, in the following code, the second `->` is not correctly linked.
```coq
Definition ty := (bool -> nat) -> unit.
```
This is because the location of the glob file starts two places off from the actual `->` location and points to the `) -> ` part. 

```coq
R29:33 Coq.Init.Logic <> ::type_scope:x_'->'_x not
```

**Comment by proux01** [comment]
If this is a bug in Coq when it generates glob files, it should be reported upstream. Or even better, open a pull request there with a fix (look for `dump_glob` to find out where glob files get generated).
