### ISSUE TITLE
links to mathcomp

### ISSUE THREAD

**Issue by affeldt-aist** [affeldt-aist/coq2html#9]
very minor: some links to mathcomp seem broken: https://math-comp.github.io/htmldoc/mathcomp.algebra.ssralg.html#GRing.Zmodule.Exports.zmodType
    (looks like it's not a coq2html bug but the fact that doc of Analysis master (still on MC1) should link to the doc of MC1 not MC master (MC2))

@proux01

**Comment by yoshihiro503** [comment]
I think this issue can be solved by specifying the version explicitly in the URL to the external library.

https://yoshihiro503.github.io/coq2html/mathcomp.classical.cardinality.html#fimfun_zmodType
